---
{{ $appLabelArgs := dict "label" "yb-master" "root" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yugabyte.fullname" . }}-master-hooks
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "yugabyte.applabel" ($appLabelArgs) | indent 4 }}
    {{- include "yugabyte.labels" . | indent 4 }}
data:
{{- range $index := until ( int ( .Values.replicas.master ) ) }}
  yb-master-{{.}}-pre_debug_hook.sh: "echo 'hello-from-pre' "
  yb-master-{{.}}-post_debug_hook.sh: "echo 'hello-from-post' "
{{- end }}
---
{{ $appLabelArgs := dict "label" "yb-tserver" "root" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yugabyte.fullname" . }}-tserver-hooks
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "yugabyte.applabel" ($appLabelArgs) | indent 4 }}
    {{- include "yugabyte.labels" . | indent 4 }}
data:
{{- range $index := until ( int ( .Values.replicas.tserver) ) }}
  yb-tserver-{{.}}-pre_debug_hook.sh: "echo 'hello-from-pre' "
  yb-tserver-{{.}}-post_debug_hook.sh: "echo 'hello-from-post' "
{{- end }}
---
